# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

powerMethodCpp <- function(X, v, eps = 1e-6, maxiter = 100L) {
    .Call('_locStra_powerMethodCpp', PACKAGE = 'locStra', X, v, eps, maxiter)
}

covCpp <- function(X) {
    .Call('_locStra_covCpp', PACKAGE = 'locStra', X)
}

jaccardMatrixCpp2 <- function(X) {
    .Call('_locStra_jaccardMatrixCpp2', PACKAGE = 'locStra', X)
}

calculateSMatrixDenseCpp <- function(X, Djac = FALSE, phased = FALSE, minVariants = 5L) {
    .Call('_locStra_calculateSMatrixDenseCpp', PACKAGE = 'locStra', X, Djac, phased, minVariants)
}

grmDenseCpp3 <- function(X, robust = TRUE) {
    .Call('_locStra_grmDenseCpp3', PACKAGE = 'locStra', X, robust)
}

covCpp_sparse <- function(T, nrows, ncols, rowStart = 0L, rowEnd = -1L) {
    .Call('_locStra_covCpp_sparse', PACKAGE = 'locStra', T, nrows, ncols, rowStart, rowEnd)
}

jaccardMatrixCpp4_sparse <- function(T, nrows, ncols) {
    .Call('_locStra_jaccardMatrixCpp4_sparse', PACKAGE = 'locStra', T, nrows, ncols)
}

calculateSMatrixCpp <- function(T, nrows, ncols, Djac = FALSE, phased = FALSE, minVariants = 5L, rowStart = 0L, rowEnd = -1L) {
    .Call('_locStra_calculateSMatrixCpp', PACKAGE = 'locStra', T, nrows, ncols, Djac, phased, minVariants, rowStart, rowEnd)
}

grmCpp_sparse <- function(T, nrows, ncols, robust = TRUE) {
    .Call('_locStra_grmCpp_sparse', PACKAGE = 'locStra', T, nrows, ncols, robust)
}

